name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] # macOS-latest, windows-latest]
        java-version: ["8", "11", "17"]
        clojure-version: ["1.11.1"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -ntp -B -Dclojure.version=${{ matrix.clojure-version }} clean test
